# Generated by Django 4.1.4 on 2022-12-22 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_fee_amount', models.FloatField(default=0.0)),
                ('pago_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_usuario', to='pagos.paymnentuser')),
            ],
            options={
                'db_table': 'pagos_vencidos',
            },
        ),
    ]
